# Generated by Django 5.2.4 on 2025-07-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('Discussion', 'Discussion'), ('Accounting', 'Accounting'), ('Conceptual', 'Conceptual')], max_length=20)),
                ('auditee_action_owner', models.CharField(max_length=255)),
                ('auditee_status', models.CharField(choices=[('Discussion', 'Discussion'), ('Accounting', 'Accounting'), ('Conceptual', 'Conceptual')], default='Discussion', max_length=20)),
                ('auditor_status', models.CharField(choices=[('Discussion', 'Discussion'), ('Accounting', 'Accounting'), ('Conceptual', 'Conceptual')], default='Discussion', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
