# Generated by Django 5.2.4 on 2025-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Auditor', 'Auditor'), ('Auditee', 'Auditee')], max_length=10),
        ),
    ]
