# Generated by Django 5.2.4 on 2025-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditquerylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditquery',
            name='auditee_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Discussion Point', 'Discussion Point')], default='Enter status', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditquery',
            name='auditor_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Discussion Point', 'Discussion Point')], default='Enter status', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditquery',
            name='query_type',
            field=models.CharField(choices=[('Discussion', 'Discussion'), ('Accounting', 'Accounting'), ('Conceptual', 'Conceptual')], default='Enter status', max_length=20),
        ),
    ]
