# Generated by Django 5.2.4 on 2025-07-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditquery_auditee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquerylog',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditquerylog',
            name='audit_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.auditquery'),
        ),
    ]
