# Generated by Django 5.2.4 on 2025-07-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auditquerylog_name_alter_auditquerylog_audit_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditQueryLog',
        ),
    ]
